version: '3.3'
services:
  alist:
    restart: always
    volumes:
      - '/etc/alist:/opt/alist/data'
    ports:
      - '5244:5244'
      #- '5245:5245'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
      #- NEZHA_SERVER=
      #- NEZHA_PORT=
      #- NEZHA_KEY=
      #- NEZHA_ARGS=
    container_name: alist
    build:
      context: .
      dockerfile: Dockerfile
