name: Dynamic Docker Build

on:
  push:
    paths:
      - 'alist-for-paas/**'
      - 'cloudflare-imgbed/**'
      #- 'another-project/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify changed projects
        id: detect_changes
        run: |
          CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d'/' -f1 | sort -u)
          echo "Changed folders: $CHANGED_FOLDERS"
          echo "changed_folders=$CHANGED_FOLDERS" >> $GITHUB_ENV

      - name: Set matrix for changed projects
        run: |
          CHANGED=${{ env.changed_folders }}
          MATRIX="["

          if [ -z "$CHANGED" ]; then
            echo "No changed folders detected."
            echo "matrix=[]" >> $GITHUB_ENV
            exit 0
          fi

          for folder in $CHANGED; do
            if [ -d "$folder" ]; then
              MATRIX="$MATRIX\"$folder\","
            fi
          done
          MATRIX="${MATRIX%,}]"
          echo "Matrix: $MATRIX"
          echo "matrix=$MATRIX" >> $GITHUB_ENV

  build:
    needs: build-and-push
    strategy:
      matrix:
        folder: ${{ fromJson(env.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.folder }}
          file: ${{ matrix.folder }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.folder }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.folder }}:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.folder }}:${{ github.run_number }}
