name: Update Docker Build Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*'  # 监听所有文件的变更

permissions:
  contents: write
  actions: write
  workflows: write  # 关键：允许修改工作流文件

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run workflow update script
        run: |
          python .github/scripts/update_workflow.py

      - name: Commit updated workflow
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/docker-build.yml
          git commit -m "Auto-update docker-build.yml with detected projects" || echo "No changes to commit"
          git push
